name: virus_titers_and_neuts

channels:
  - conda-forge
  - bioconda

dependencies:
  - python
  - jupyterlab
  - pandas
  - numpy
  - seaborn
  - scipy
  - altair
  - scikit-learn
  - openpyxl
  - pip
  - pip:
    - neutcurve==0.5.7